apiVersion: apps/v1
kind: Deployment

metadata:
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-gke
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
        - name: app
          image: gcr.io/liverpool-monitor/$IMAGE:$GITHUB_SHA
          imagePullPolicy: Always